#服务端口
server:
  port: 8003
spring:
  application:
    name: service-vod-8003
  profiles:
    active: dev #环境设置：dev、test、prod
  servlet:
    multipart:
      max-file-size: 1024MB  # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB  # 最大置总上传的数据大小 ：默认10M
#阿里云 vod
aliyun:
  vod:
    file:
      keyid: yourkeyid
      keysecret: yourkeysecret