#服务端口
server:
  port: 8002
spring:
  application:
    name: service-oss-8002
  profiles:
    active: dev #环境设置：dev、test、prod
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: yourkeyid
      keysecret: yourkeysecret
      bucketname: guli-edu-teacher