#服务端口
server:
  port: 8005
spring:
  application:
    name: service-msm-8005
  profiles:
    active: dev #环境设置：dev、test、prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_institude?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 39.104.117.161
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:  #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:top/chenbn/guli/mapper/xml/*.xml
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl